spring:
  application:
    name: catalog
  config:
    import: classpath:.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/eda?useSSL=false
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_HOST}
      database: eda
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  kafka:
    bootstrap-servers:
      - localhost:19092
      - localhost:19093
      - localhost:19094
    consumer:
      group-id: eda-group1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8085

